external_auth:
  pam:
    saltops-prod:
      - '@jobs'
      - 'pkg.install'
      - 'pkg.upgrade'
      - 'service.restart'
    saltops-staging:
      - '@jobs'
      - 'pkg.install'
      - 'pkg.upgrade'
      - 'service.restart'
    saltops-monitoring:
      - '@jobs'
      - 'service.restart'
