INSERT INTO items (name) VALUES
  ('Laptop'),
  ('Desktop / CPU'),
  ('RAM'),
  ('Storage (SSD)'),
  ('Networking Devices'),
  ('Network Accessories'),
  ('Mouse'),
  ('Keyboard'),
  ('Audio Devices'),
  ('Monitor / Display'),
  ('Cables & Adapters'),
  ('Power & Electrical'),
  ('Docking & Hubs'),
  ('Pendrive'),
  ('Printers & Cartridges'),
  ('Scanners'),
  ('Tools'),
  ('Miscellaneous')
ON CONFLICT (name) DO NOTHING;

WITH seeded(main_item_name, sub_item_name, item_code) AS (
  VALUES
    ('Laptop', 'Thinkpad I5', 'LAP-THINKPADI5'),
    ('Laptop', 'Thinkpad X1 Carbon', 'LAP-THINKPADX1'),
    ('Laptop', 'Thinkpad T14 I7', 'LAP-T14I7'),
    ('Laptop', 'Thinkpad E14', 'LAP-THINKPADE14'),
    ('Laptop', 'Dell I5 Latitude', 'LAP-DELLLATI5'),
    ('Laptop', 'Laptop X1', 'LAP-X1'),
    ('Laptop', 'Generic Laptop', 'LAP-GENERIC'),
    ('Desktop / CPU', 'CPU i7', 'CPU-I7'),
    ('Desktop / CPU', 'Dell Optiplex I3 CPU', 'CPU-OPTIPLEXI3'),
    ('Desktop / CPU', 'NUC i3 CPU', 'CPU-NUCI3'),
    ('Desktop / CPU', 'NUC i5 CPU', 'CPU-NUCI5'),
    ('RAM', '8GB DDR4 RAM', 'RAM-8GBDDR4'),
    ('RAM', '16GB DDR4 RAM', 'RAM-16GBDDR4'),
    ('RAM', '32GB DDR4 RAM', 'RAM-32GBDDR4'),
    ('RAM', '16GB DDR5 RAM', 'RAM-16GBDDR5'),
    ('RAM', '32GB DDR5 RAM', 'RAM-32GBDDR5'),
    ('Storage (SSD)', '120GB SSD', 'SSD-120GB'),
    ('Storage (SSD)', '240GB SSD', 'SSD-240GB'),
    ('Storage (SSD)', '512GB SSD M.2', 'SSD-512GBM2'),
    ('Mouse', 'Wired Mouse', 'MSE-WIRED'),
    ('Mouse', 'Wireless Mouse', 'MSE-WIRELESS'),
    ('Mouse', 'Wireless Keyboard and Mouse Combo', 'MSE-KBCOMBO'),
    ('Keyboard', 'Keyboard', 'KBD-GENERIC'),
    ('Keyboard', 'Wired Keyboard', 'KBD-WIRED'),
    ('Audio Devices', 'Headset Sennheiser', 'AUD-SENNHEISER'),
    ('Audio Devices', 'Logitech Mic Pod', 'AUD-LOGIMICPOD'),
    ('Monitor / Display', 'Dell Monitor', 'MON-DELL'),
    ('Monitor / Display', 'Samsung 27 Inch Monitor', 'MON-SAMSUNG27'),
    ('Monitor / Display', 'BenQ 24" Monitor', 'MON-BENQ24'),
    ('Cables & Adapters', 'HDMI Cable 1 Meter', 'CBL-HDMI1M'),
    ('Cables & Adapters', 'HDMI Cable 15 Meter', 'CBL-HDMI15M'),
    ('Cables & Adapters', 'HDMI to VGA Adapter', 'CBL-HDMIVGA'),
    ('Cables & Adapters', 'D to HDMI Converter', 'CBL-DTOHDMI'),
    ('Cables & Adapters', 'Display Port Cable', 'CBL-DISPLAYPORT'),
    ('Cables & Adapters', 'USB Type-C to HDMI Cable', 'CBL-USBCHDMI'),
    ('Cables & Adapters', 'Type-C Cable', 'CBL-TYPEC'),
    ('Cables & Adapters', 'USB-C Male to Female', 'CBL-USBCMF'),
    ('Cables & Adapters', 'Printer USB Cable', 'CBL-PRNUSB'),
    ('Networking Devices', 'Router', 'NET-ROUTER'),
    ('Networking Devices', 'TP-Link 8 Port Switch', 'NET-TP8SW'),
    ('Networking Devices', 'D-Link 24 Port Switch', 'NET-DL24SW'),
    ('Networking Devices', 'Ruijie Access Point', 'NET-RUIJIEAP'),
    ('Network Accessories', 'USB LAN', 'NAC-USBLAN'),
    ('Network Accessories', 'LAN Cable', 'NAC-LANCABLE'),
    ('Network Accessories', 'Ethernet Cable', 'NAC-ETHERNET'),
    ('Network Accessories', 'WiFi Adapter', 'NAC-WIFIADAPT'),
    ('Power & Electrical', 'Spike Buster', 'PWR-SPIKEBSTR'),
    ('Power & Electrical', 'Atom SMPS V450', 'PWR-ATOMV450'),
    ('Power & Electrical', 'CMOS Battery', 'PWR-CMOSBAT'),
    ('Power & Electrical', 'Lenovo Charger', 'PWR-LNVCHARGER'),
    ('Power & Electrical', 'Lenovo Battery', 'PWR-LNVBATTERY'),
    ('Power & Electrical', 'PDU', 'PWR-PDU'),
    ('Docking & Hubs', 'Dell Docking Station', 'DOC-DELLDOCK'),
    ('Docking & Hubs', 'USB-C Docking Station', 'DOC-USBCDOCK'),
    ('Docking & Hubs', 'USB Hub', 'DOC-USBHUB'),
    ('Pendrive', '16GB Pendrive', 'PEN-16GB'),
    ('Pendrive', '32GB Pendrive', 'PEN-32GB'),
    ('Pendrive', '64GB Pendrive', 'PEN-64GB'),
    ('Printers & Cartridges', 'Brother Label DK-22210', 'PRN-DK22210'),
    ('Printers & Cartridges', 'Brother Cartridge 263', 'PRN-BRO263'),
    ('Printers & Cartridges', 'Brother Cartridge 269', 'PRN-BRO269'),
    ('Printers & Cartridges', 'HP LaserJet Cartridges', 'PRN-HPLASER'),
    ('Printers & Cartridges', 'Canon Cartridges', 'PRN-CANON'),
    ('Scanners', 'TVS Scanner', 'SCN-TVS'),
    ('Scanners', 'Canon LIDE 300', 'SCN-LIDE300'),
    ('Scanners', 'Canon DR-C240', 'SCN-DRC240'),
    ('Scanners', 'Finger Scanner', 'SCN-FINGER'),
    ('Tools', 'Laptop Tool Kit', 'TLS-LAPKIT'),
    ('Tools', 'Screwdriver Set', 'TLS-SCREWSET'),
    ('Miscellaneous', 'Mousepad', 'MSC-MOUSEPAD'),
    ('Miscellaneous', 'Apple Connector', 'MSC-APPLECONN'),
    ('Miscellaneous', 'Formujet Cartridge', 'MSC-FORMUJET'),
    ('Miscellaneous', 'Wire Management Clip', 'MSC-WIRECLIP')
)
INSERT INTO sub_items (item_id, name, item_code, asset_type)
SELECT i.id, seeded.sub_item_name, seeded.item_code, 'non_critical'
FROM seeded
JOIN items i ON i.name = seeded.main_item_name
ON CONFLICT (item_id, name) DO NOTHING;