#!/usr/bin/env bash
#
# install-itms-netdata.sh
# Install Netdata for real-time system metrics monitoring
#
# Usage:
#   sudo ./scripts/install-itms-netdata.sh
#
# What this does:
# - Installs Netdata using the official one-line installer
# - Configures REST API access on port 19999
# - Enables systemd service for automatic startup
# - Configures firewall rules (if firewalld is active)
# - Provides integration endpoints for ITMS backend
#
# Dependencies: curl, bash, systemd
# Port: 19999 (Netdata REST API)
#

set -euo pipefail

NETDATA_PORT="${NETDATA_PORT:-19999}"
NETDATA_BIND="${NETDATA_BIND:-0.0.0.0}"
ITMS_SERVER="${ITMS_SERVER:-YOUR_SERVER_IP}"

# Color output
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly BLUE='\033[0;34m'
readonly NC='\033[0m' # No Color

log_info() {
  echo -e "${BLUE}[INFO]${NC} $*"
}

log_success() {
  echo -e "${GREEN}[SUCCESS]${NC} $*"
}

log_warn() {
  echo -e "${YELLOW}[WARN]${NC} $*"
}

log_error() {
  echo -e "${RED}[ERROR]${NC} $*"
}

# Check if running as root
if [[ $EUID -ne 0 ]]; then
  log_error "This script must be run as root (use sudo)"
  exit 1
fi

# Detect OS
if [[ -f /etc/os-release ]]; then
  . /etc/os-release
  OS_NAME="${ID}"
  OS_VERSION="${VERSION_ID}"
else
  log_error "Cannot detect OS. /etc/os-release not found."
  exit 1
fi

log_info "Detected OS: ${OS_NAME} ${OS_VERSION}"

# Check if Netdata is already installed
if command -v netdata &>/dev/null; then
  log_warn "Netdata is already installed. Checking configuration..."
  NETDATA_VERSION=$(netdata -V 2>&1 | head -n1 || echo "Unknown")
  log_info "Installed version: ${NETDATA_VERSION}"
  
  if systemctl is-active --quiet netdata; then
    log_success "Netdata service is running"
    
    # Test API endpoint
    if curl -sf "http://localhost:${NETDATA_PORT}/api/v1/info" &>/dev/null; then
      log_success "Netdata REST API is accessible at http://localhost:${NETDATA_PORT}"
      log_info "Integration endpoint: http://localhost:${NETDATA_PORT}/api/v1/data"
      exit 0
    else
      log_warn "Netdata is running but API is not accessible. Reconfiguring..."
    fi
  else
    log_warn "Netdata is installed but not running. Starting service..."
    systemctl start netdata
    systemctl enable netdata
  fi
else
  log_info "Installing Netdata..."
  
  # Download and run Netdata installer
  # Official kickstart script from: https://github.com/netdata/netdata
  log_info "Downloading Netdata kickstart installer..."
  
  curl -Ss https://my-netdata.io/kickstart.sh -o /tmp/netdata-kickstart.sh
  
  if [[ ! -f /tmp/netdata-kickstart.sh ]]; then
    log_error "Failed to download Netdata installer"
    exit 1
  fi
  
  log_info "Running Netdata installer (this may take a few minutes)..."
  
  # Run installer with non-interactive mode
  bash /tmp/netdata-kickstart.sh --dont-wait --stable-channel --disable-telemetry
  
  # Clean up installer
  rm -f /tmp/netdata-kickstart.sh
  
  log_success "Netdata installation completed"
fi

# Configure Netdata
log_info "Configuring Netdata..."

NETDATA_CONF="/etc/netdata/netdata.conf"
NETDATA_CONF_DIR="/etc/netdata"

# Create config directory if it doesn't exist
mkdir -p "${NETDATA_CONF_DIR}"

# Initialize netdata.conf if it doesn't exist
if [[ ! -f "${NETDATA_CONF}" ]]; then
  log_info "Generating default configuration..."
  netdata -W set 2>/dev/null || true
fi

# Backup original config
if [[ -f "${NETDATA_CONF}" ]] && [[ ! -f "${NETDATA_CONF}.backup" ]]; then
  cp "${NETDATA_CONF}" "${NETDATA_CONF}.backup"
  log_info "Original config backed up to ${NETDATA_CONF}.backup"
fi

# Configure API access
log_info "Configuring REST API access on ${NETDATA_BIND}:${NETDATA_PORT}..."

# Update netdata.conf settings
cat > "${NETDATA_CONF_DIR}/netdata.conf" <<EOF
# ITMS Netdata Configuration
# Generated by install-itms-netdata.sh

[global]
    # Run as netdata user/group
    run as user = netdata
    
    # Web server bind address and port
    bind to = ${NETDATA_BIND}
    default port = ${NETDATA_PORT}
    
    # Enable web server
    mode = web
    
    # Memory settings
    memory mode = dbengine
    page cache size = 32
    dbengine disk space = 256
    
    # Update frequency (1 second default)
    update every = 1
    
    # History retention
    history = 3600

[web]
    # Allow access from ITMS server
    allow connections from = localhost 127.0.0.1 ::1 ${ITMS_SERVER}
    
    # Enable REST API
    enable gzip compression = yes
    
[plugins]
    # Enable core collectors
    proc = yes
    diskspace = yes
    cgroups = yes
    tc = no
    idlejitter = no
    
[plugin:proc]
    /proc/net/dev = yes
    /proc/diskstats = yes
    /proc/meminfo = yes
    /proc/vmstat = yes
    /proc/stat = yes
    /proc/uptime = yes
    /proc/loadavg = yes
    
[plugin:proc:/proc/diskstats]
    enable new disks detected at runtime = yes
    
[plugin:proc:/proc/net/dev]
    enable new interfaces detected at runtime = yes
EOF

log_success "Netdata configuration updated"

# Set proper permissions
chown -R netdata:netdata "${NETDATA_CONF_DIR}"
chmod 0755 "${NETDATA_CONF_DIR}"
chmod 0644 "${NETDATA_CONF}"

# Configure firewall (if firewalld is active)
if systemctl is-active --quiet firewalld; then
  log_info "Configuring firewall rules for Netdata..."
  
  if ! firewall-cmd --list-ports | grep -q "${NETDATA_PORT}/tcp"; then
    firewall-cmd --permanent --add-port="${NETDATA_PORT}/tcp" || log_warn "Failed to add firewall rule"
    firewall-cmd --reload || log_warn "Failed to reload firewall"
    log_success "Firewall configured to allow port ${NETDATA_PORT}"
  else
    log_info "Firewall rule for port ${NETDATA_PORT} already exists"
  fi
fi

# Enable and restart Netdata service
log_info "Enabling and restarting Netdata service..."
systemctl daemon-reload
systemctl enable netdata
systemctl restart netdata

# Wait for service to be ready
sleep 3

# Verify installation
log_info "Verifying Netdata installation..."

if systemctl is-active --quiet netdata; then
  log_success "✓ Netdata service is running"
else
  log_error "✗ Netdata service failed to start"
  systemctl status netdata --no-pager
  exit 1
fi

# Test API endpoint
if curl -sf "http://localhost:${NETDATA_PORT}/api/v1/info" &>/dev/null; then
  log_success "✓ Netdata REST API is accessible"
else
  log_error "✗ Netdata API is not responding on http://localhost:${NETDATA_PORT}"
  log_info "Check logs: journalctl -u netdata -n 50"
  exit 1
fi

# Get system info from Netdata
log_info "Fetching system metrics sample..."
SYSTEM_INFO=$(curl -s "http://localhost:${NETDATA_PORT}/api/v1/info" | grep -o '"hostname":"[^"]*"' | cut -d'"' -f4 || echo "unknown")

log_success "Netdata monitoring is now active for host: ${SYSTEM_INFO}"

# Display integration information
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
log_success "Netdata Installation Complete!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Dashboard Access:"
echo "  Local:    http://localhost:${NETDATA_PORT}"
echo "  Remote:   http://$(hostname -I | awk '{print $1}'):${NETDATA_PORT}"
echo ""
echo "REST API Endpoints:"
echo "  Info:     http://localhost:${NETDATA_PORT}/api/v1/info"
echo "  Data:     http://localhost:${NETDATA_PORT}/api/v1/data?chart=system.cpu"
echo "  Charts:   http://localhost:${NETDATA_PORT}/api/v1/charts"
echo "  Alarms:   http://localhost:${NETDATA_PORT}/api/v1/alarms"
echo ""
echo "Example Metrics Queries:"
echo "  CPU:      curl -s 'http://localhost:${NETDATA_PORT}/api/v1/data?chart=system.cpu&after=-60'"
echo "  Memory:   curl -s 'http://localhost:${NETDATA_PORT}/api/v1/data?chart=system.ram&after=-60'"
echo "  Disk:     curl -s 'http://localhost:${NETDATA_PORT}/api/v1/data?chart=system.io&after=-60'"
echo "  Network:  curl -s 'http://localhost:${NETDATA_PORT}/api/v1/data?chart=system.net&after=-60'"
echo ""
echo "ITMS Backend Integration:"
echo "  1. Create backend/services/netdata.go to fetch live metrics"
echo "  2. Add GET /api/devices/:id/metrics/live endpoint"
echo "  3. Frontend can poll this endpoint from DeviceDetailPage"
echo ""
echo "Service Management:"
echo "  Status:   sudo systemctl status netdata"
echo "  Restart:  sudo systemctl restart netdata"
echo "  Logs:     sudo journalctl -u netdata -f"
echo "  Stop:     sudo systemctl stop netdata"
echo ""
echo "Configuration:"
echo "  Config:   ${NETDATA_CONF}"
echo "  Backup:   ${NETDATA_CONF}.backup"
echo "  Edit:     sudo vi ${NETDATA_CONF}"
echo ""
log_info "Netdata is ready for ITMS integration!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
